app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    comment_id = db.Column(db.Integer,db.ForeignKey('comments.id'))
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure,password)



    def __repr__(self):
        return f'User {self.username}'


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String(255))
    pitch_field = db.Column(db.String())
    users = db.relationship('User',backref = 'comment',lazy = "dynamic")


    def __repr__(self):
        return f'User {self.pitch_field}'


class PICKUPLINES:
    all_pickuplines = []
    def __init__(self,title,pitch):
        self.title = title
        self.pitch = pitch

    def save_pickupline(self):
        PICKUPLINES.all_pickuplines.append(self)


    @classmethod
    def clear_pitchs(cls):
        PICKUPLINES.all_pickuplines.clear()


    @classmethod
    def get_pitchs(cls):

        response = []

        for pitchs in cls.all_pickuplines:
            response.append(pitchs)

        return response
        


class INTERVIEW:
    all_interview = []
    def __init__(self,title,pitch):
        self.title = title
        self.pitch = pitch

    def save_interview(self):
        INTERVIEW.all_interview.append(self)


    @classmethod
    def clear_pitchs(cls):
        PICKUPLINES.all_pickuplines.clear()


    @classmethod
    def get_pitchs(cls):

        response = []

        for pitchs in cls.all_interview:
            response.append(pitchs)

        return response


class BUSINESSPLAN:
    all_businessplan = []
    def __init__(self,title,pitch):
        self.title = title
        self.pitch = pitch

    def save_businessplan(self):
        BUSINESSPLAN.all_businessplan.append(self)


class COMMENT:
    all_comments = []
    def __init__(self, id, title, comment, user):
        self.id = id
        self.title = title
        self.comment = comment
        self.comment = comment
        self.user = user

    def save_interview(self):
        INTERVIEW.all_interview.append(self)


    @classmethod
    def clear_pitchs(cls):
        PICKUPLINES.all_pickuplines.clear()


    @classmethod
    def get_pitchs(cls):

        response = []

        for pitchs in cls.all_interview:
            response.append(pitchs)

        return response

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required

class PickUpLines(FlaskForm):

    title = StringField('Pickup lines title',validators=[Required()])
    pitch = TextAreaField('Pickup lines pitch',validators=[Required()])
    submit = SubmitField('Submit')


class Interview(FlaskForm):

    title = StringField('Interview title',validators=[Required()])
    pitch = TextAreaField('Interview pitch',validators=[Required()])
    submit = SubmitField('Submit')


class BusinessPlan(FlaskForm):

    title = StringField('Business plan title',validators=[Required()])
    pitch = TextAreaField('Business plan pitch',validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):

    bio = TextAreaField('More about you', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):

    comments = TextAreaField('Leave your comment', validators=[Required()])
    submit = SubmitField("Leave your comment")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

# Initializing application
def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Register the blueprint
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    from .models import PICKUPLINES
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template, url_for, redirect, request, abort
from . import main
from .forms import PickUpLines, Interview, BusinessPlan
from ..models import PICKUPLINES, INTERVIEW, User
from .. import db
from flask_login import login_required

@main.route('/')
def index():

    '''
    view root page function that returns the index page and its data
    '''
    
    title = 'Your best pitching site'
    message = 'Write your Pitch'
    return render_template('index.html',title = title,message = message)


@main.route('/pitch')
def pitch():
    
    '''
    view pitch page function that returns the pitch page and its data
    '''

    title = 'Pitching best ideas'
    
    return render_template('pitch.html', title = title)


@main.route('/business_plan', methods = ['GET','POST'])
@login_required
def business_plan():
    form = BusinessPlan()
    '''
    view business_plan function that returns the business_plan page and its data
    '''

    title = 'Business Plan'

    return render_template('business_plan.html', title = title, business_plan_form = form)


@main.route('/interview')
@login_required
def interview():
    form = Interview()
    '''
    view interview function that returns the interview page and its data
    '''

    title = 'Interview'

    return render_template('interview.html', title = title,interview_form = form)


@main.route('/pick_up_lines')
@login_required
def pick_up_lines():
    form = PickUpLines()
    '''
    view pick_up_lines function that returns the pick_up_lines page and its data
    '''

    title = 'Pick Up Lines'

    return render_template('pick_up_lines.html', title = title, pickup_lines_form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/business_plan.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pitching best ideas</title>
</head>
<body>
    <div class="container">
        {% block content %}
        <div class="row">
            <div class="col-md-12">
                <h3>Business Plan</h3>
                {{wtf.quick_form(business_plan_form)}}
            </div>
        </div>

        {% endblock %}
    </div>
    
</body>
</html>

app/templates/index.html
{% extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Your best pitching site</title>
</head>
<body>
    {% block content %}
    <div class="container-fluid">

        <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">ONE MINUTE PITCH</h1>
              <p class="lead">In life, you only have 60 seconds to impress someone. 1 minute can either make or break you. You only live once, but if you do it right, once is enough.</p>
            </div>
        </div>

            <div class="row">
                <div class="col-md-12">
                    <h3>{{message}}</h3>
                    <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.pitch') }}">Click here to write your Pitch</a>
                </div>
            </div>
    
    </div>
    {% endblock %}
</body>
</html>

app/templates/interview.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pitching best ideas</title>
</head>
<body>
    <div class="container">
        {% block content %}
        <div class="row">
            <div class="col-md-12">
                <h3>Interview</h3>
                {{wtf.quick_form(interview_form)}}
            </div>
        </div>

        {% endblock %}
    </div>
    
</body>
</html>

app/templates/macros.html
<!-- {% macro displayPitch(pitch_list) %}

    {% for pitch in pitchlist %}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                {pitch.PickUpLines}
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                {pitch.Interview}
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                
            </div>
        </div>
    {% endfor %}

{% endmacro %} -->

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> Pitch </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
            </div>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li style="color: white;padding: 15px;">{{current_user.username}}</li>
              <li><a href="{{url_for('auth.logout')}}"></a> Sign out</li>
              {% else %}
              <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
              {%endif%}
            </ul>

        </div>
    </div>
  </body>
</html>

app/templates/pick_up_lines.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pitching best ideas</title>
</head>
<body>
    <div class="container">
        {% block content %}
        <div class="row">
            <div class="col-md-12">
                <h3>Pickup Lines</h3>
                {{wtf.quick_form(pickup_lines_form)}}
            </div>
        </div>

        {% endblock %}
    </div>
    
</body>
</html>

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/pitch.css')}}">
{% endblock%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pitching best ideas</title>
</head>
<body>
    {% block content %}
    <h3>Choose your best</h3>
    <div class = "row">
        <div class = "col-md -12">
            <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.business_plan') }}">Click here to write your Business Plan Pitch</a>
        </div>
        <hr/>
        <div class = "col-md -12">
            <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.interview') }}">Click here to write your interview Pitch</a>
        </div>
        <hr/>
        <div class = "col-md -12">
            <a class="btn btn-success btn-lg text-center" href="{{ url_for('main.pick_up_lines') }}">Click here to write your Pick Up Lines Pitch</a>
        </div>
    </div>
    {% endblock %}
</body>
</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}